### PR TITLE
Adding options for username and password

### PR DESCRIPTION
**Pull request by mattdodge**

### CODE REVIEW

**Comment by hansmosh** [comment]
I know sometimes it can be tricky to write unit tests for these things, but would it be pretty straight forward to write a test to check that Elasticsearch is created with the appropriate url?

**Comment by mattdodge** [comment]
Yeah, I'll add some. I made this change a while ago and it's been in use on the media project for a while and didn't realize it hadn't been merged so I created this PR

**Comment by hansmosh** [comment]
This guy still needs a unit test. Plus, it's not able to be merged anymore.

**Comment by hansmosh** [comment]
@mattdodge I went ahead and added a unit test for this. Could you take a quick look and merge if ready? Thanks.

**Comment by mattdodge** [comment]
Nice, these look great :+1:

**Pull request merged**
